# yazi.toml
[mgr]
show_hidden = true
ratio = [1, 2, 3]

[[mgr.prepend_keymap]]
on = "!"
for = "unix"
run = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[opener.set-wallpaper]]
run = "awww img %s1"
for = "linux"
desc = "Set as wallpaper using awww"
orphan = true

[[open.prepend_rules]]
mime = "image/*"
use = ["set-wallpaper", "open"]
